feat: update cabonapi to c2229eabd094
moira-alert/moira pull request #1074
Opened 2024-08-22 08:28 UTC by Tetrergeru

TODO

2024-08-23 08:53 UTC, Tetrergeru commented
/build

2024-09-10 15:11 UTC, Tetrergeru commented
/build

2024-09-11 05:11 UTC, AleksandrMatsko requested changes
Надушниль

2024-09-17 08:07 UTC, almostinf commented on metric_source/local/eval.go
> +	metrics  []string
почему решил добавить метрики внутрь этой структуры, а не возвращать из Fetch? Можно было бы сделать какой-нибудь `fetchResult` с метриками и metricsMap

2024-09-17 08:18 UTC, almostinf commented on metric_source/local/eval.go
> +		md := newMetricDataFromGraphit(metricData, len(result.Metrics) != len(result.Patterns))
`newMetricDataFromGraphit` -> `newMetricDataFromGraphite`

2024-09-17 08:23 UTC, almostinf commented on metric_source/metric_data.go
> +	// TODO(Tetrergeru) Wtf is a wildcard in this context
Судя по коду параметр определяет были ли вайлдкард в запросе, проверка на то равно ли количество паттерном количеству метрик

2024-09-17 08:32 UTC, almostinf commented on metric_source/local/local_test.go
> +		result, err := localSource.Fetch("alias(movingMin(apps.*.process.cpu.usage, '20s'), 'min')", from, until, true)
Не очень много тестов на функции, которые были изменены в ходе релиза. Как будто бы точно стоит покрыть тестами moving* функции с числовым и не числовым параметрами, hitcount, smartSummarize, keepLastValue и тд. Это точно будет не лишним, тк лучше будем понимать и видеть в тестах, какие функции изменились и как это может сказаться на уже существующих триггерах

2024-09-18 10:12 UTC, kissken commented on go.mod
> +	github.com/go-graphite/carbonapi v0.16.2-0.20240530091606-c2229eabd094
а почему на коммит еще?

2024-09-18 10:24 UTC, kissken commented on go.mod
> +	github.com/go-graphite/carbonapi v0.16.2-0.20240530091606-c2229eabd094
я прост может забыла, давай просто где-нибудь напишем, чего мы так решили сделать)

2024-10-02 09:06 UTC, Tetrergeru commented on metric_source/local/eval.go
> +		return merry.Unwrap(err)
Там предлагается заменять на As/Is, но это не оч подходит под наш юзкейс. В карбонапи, к сожалению, используется эта штука, может надо в будущем посмотреть в сторону того, куда это переделать

2024-10-02 09:07 UTC, Tetrergeru commented on metric_source/local/eval.go
> +func (eval *evaluator) Fetch(
Поправил

2024-10-02 09:07 UTC, Tetrergeru commented on metric_source/local/eval.go
> +func NewFetchCtx(from, until int64) *fetchCtx {
Сделал

2024-10-02 09:08 UTC, Tetrergeru commented on metric_source/local/eval.go
> +type fetchCtx struct {
Не вижу смысла. Файл довольно небольшой, логически она очень тесно связана с происходящим в нём

2024-10-02 09:09 UTC, Tetrergeru commented on metric_source/local/timer.go
Сделал всё приватным и удалил годоки

2024-10-02 09:09 UTC, Tetrergeru commented on metric_source/local/timer.go
> +	// var until int64
Да, это я тупанул чёт, удалил

2024-10-02 09:09 UTC, Tetrergeru commented on metric_source/local/eval.go
> +		md := newMetricDataFromGraphit(metricData, len(result.Metrics) != len(result.Patterns))
Пофиксил

2024-10-02 09:17 UTC, Tetrergeru commented on metric_source/metric_data.go
> +	// TODO(Tetrergeru) Wtf is a wildcard in this context
Да, это же я и писал код, который это проверяет :sweat_smile: 
Это устаревший комментарий, который я оставил, чтобы не забыть проверить, что тут всё хорошо, удалил

2024-10-02 09:19 UTC, Tetrergeru commented on go.mod
> +	github.com/go-graphite/carbonapi v0.16.2-0.20240530091606-c2229eabd094
Не совсем понял вопрос. У карбонапи нет свежей релизной версии, так что остаётся только к коммиту привязываться

2024-10-03 07:53 UTC, kissken commented on database/redis/notification.go
> +const NotificationsLimitUnlimited = int64(-1)
кажись можно приватить

2024-10-03 08:40 UTC, Tetrergeru commented on database/redis/notification.go
> +const NotificationsLimitUnlimited = int64(-1)
Сделал

2024-10-03 08:41 UTC, Tetrergeru commented on metric_source/local/local_test.go
> +		result, err := localSource.Fetch("alias(movingMin(apps.*.process.cpu.usage, '20s'), 'min')", from, until, true)
Прошёлся по диффу карбонапи от версии 1.16.0 до той, до которой мы обновляемся и дописал тесты для фсех функций, в которых были какие-то серьёзные изменения

Тесты писал в файле `database_test.go`, потому что они используют реальную базу, в которую я предварительно сохраняю метрики

2024-10-03 08:42 UTC, Tetrergeru commented on metric_source/local/eval.go
> +	metrics  []string
Так фетч же реализует интерфейс из карбонапи, я не могу оттуда что-то новое вернуть

2024-10-03 08:42 UTC, Tetrergeru commented on metric_source/local/local.go
Поправил

2024-10-04 09:30 UTC, AleksandrMatsko submitted a review, later dismissed

2024-10-04 11:32 UTC, almostinf commented on database/redis/notification.go
> +// Separate const to prevent cyclic dependencies.
без контекста сложно понять, о какой циклической зависимости идет речь, можно чуть подробнее расписать

2024-10-04 12:45 UTC, Tetrergeru commented on database/redis/notification.go
> +// Separate const to prevent cyclic dependencies.
Расширил комментарий тут и добавил ещё один у оригинальной переменной. Когда будем обсуждать изменение структуры репозитория, надо будет учесть, что такие штуки тоже бывают

2024-10-07 10:03 UTC, Tetrergeru commented
/build

2024-10-07 17:46 UTC, Tetrergeru commented
/build

2024-10-08 08:18 UTC, kissken approved these changes

2024-10-08 08:18 UTC, AleksandrMatsko approved these changes

2024-10-08 08:18 UTC, merged