feat(api): add emergency contacts database functions
moira-alert/moira pull request #1081
Opened 2024-09-10 10:24 UTC by almostinf

# Add emergency contacts database functions

2024-09-11 03:39 UTC, AleksandrMatsko approved these changes

2024-09-18 09:28 UTC, kissken commented on database/redis/contact.go
> +		return nil, fmt.Errorf("failed to get contacts by id: %w", err)
давай идентификатор в ошибку засунем или он вернется?

2024-09-18 09:29 UTC, kissken commented on database/redis/contact.go
> +		result := pipe.Get(ctx, contactKey(id))
здесь не подойдет переиспользовать метод GetContact?

2024-09-18 09:34 UTC, kissken commented on datatypes.go
> +// EmergencyContactType are Moira's special internal types of problems.
есть предложение, прекратить это дело плодить, завести папку 
обозвать дататайп (выберете лучшее название)

в этом пр все, что касается эмергенси контанкта унести туда
отдельно раздербанить этот жирный файл на кучу файлов в папке

2024-09-18 09:35 UTC, almostinf commented on database/redis/contact.go
> +		result := pipe.Get(ctx, contactKey(id))
pipeline нужен для эффективной работы функции, чтобы не делать 100 запросов на получение определенного контакта, а всего 1

2024-09-18 09:36 UTC, kissken commented on database/redis/reply/emergency_contact.go
> +func EmergencyContact(rep *redis.StringCmd) (moira.EmergencyContact, error) {
где-то потерян глагол

2024-09-18 09:36 UTC, almostinf commented on database/redis/contact.go
> +		return nil, fmt.Errorf("failed to get contacts by id: %w", err)
так там получение нескольких контактов же, идентификаторов много может быть

2024-09-18 09:36 UTC, kissken commented on database/redis/reply/emergency_contact.go
> +func EmergencyContacts(rep []*redis.StringCmd) ([]*moira.EmergencyContact, error) {
тут тоже потерян глагол

нужна как публичная?

2024-09-18 09:37 UTC, kissken commented on database/redis/reply/emergency_contact.go
> +func EmergencyContact(rep *redis.StringCmd) (moira.EmergencyContact, error) {
нужна как публичная?

2024-09-18 09:46 UTC, kissken commented on datatypes.go
> +const (
зачем пользователю так размазывать?


ему норм ответ - работает ли мойра или нет и все

2024-09-18 09:46 UTC, kissken commented on datatypes.go
> +const (
давайте не будем вводить кучу статусов

2024-09-18 09:55 UTC, almostinf commented on datatypes.go
> +const (
Кажется, в диздоке мы сошлись на том, что типов проблем может быть много, на текущий момент их 5: не работает база, нет метрик, не работает чекер, не работает локальный чекер, не работает нотифаер. Пользователь будет видеть только разрешенный для выбора тип проблем (например, только отключение нотифаера, как оно будет называться в UI другой вопрос). Админы могут выбрать любой тип проблем. Это будет в другом PR

2024-09-18 10:18 UTC, kissken commented on database/redis/contact.go
> +		return nil, fmt.Errorf("failed to get contacts by id: %w", err)
а, проглядела, что-то думала внутри цикла

2024-09-18 10:19 UTC, kissken commented on datatypes.go
> +const (
я не вижу этого текста в ДД, ткнешь меня в ММ этим? :(

2024-09-20 13:50 UTC, Tetrergeru commented on database/redis/contact.go
> +		return contact, fmt.Errorf("failed to reply contact '%s': %w", id, err)
Апочему эта штука называется `reply`? Точно надо в такой форме в сообщении об ошибке писать?

2024-09-20 13:54 UTC, Tetrergeru commented on database/redis/contact.go
> +	if getEmergencyContactErr != nil && !errors.Is(getEmergencyContactErr, database.ErrNil) {
Если есть эмёрдженси контакт -- мы удаляем и его? Может логика должна быть наоборот, как с подписками и контактами: сначала удалите все зависимости, а потом только удаляйте контакты

2024-09-20 13:57 UTC, Tetrergeru commented on database/redis/emergency_contact.go
> +			return err
А тут не хотим кастомное сообщение об ошибке, раз везде добавляем?

2024-09-20 13:58 UTC, Tetrergeru commented on database/redis/emergency_contact.go
> +			return err
Или это типа наша же функция, а не на границе с либой, так что не будем лишнюю переобёртку делать?

2024-09-20 13:59 UTC, Tetrergeru commented on database/redis/emergency_contact.go
> +func saveEmergencyContactPipe(ctx context.Context, pipe redis.Pipeliner, emergencyContact moira.EmergencyContact) error {
По названию супер не понятно, что происходит создание пайпа, а не действие сохранение. С `removeEmergencyContactPipe` то же самое

2024-09-20 14:02 UTC, Tetrergeru commented on database/redis/emergency_contact.go
> +func saveEmergencyContactPipe(ctx context.Context, pipe redis.Pipeliner, emergencyContact moira.EmergencyContact) error {
Может сделать что-то типа "addSaveEmergencyContactToPipe"...

2024-09-20 14:03 UTC, Tetrergeru commented on datatypes.go
> +// EmergencyContactType are Moira's special internal types of problems.
Лайк

2024-09-23 09:09 UTC, almostinf commented on datatypes.go
> +// EmergencyContactType are Moira's special internal types of problems.
Мне кажется, имеет смысл вынести это в отдельный PR, так как если я делаю папку `datatypes` и добавлю туда файлы `datatypes.go` и `emergency_contacts.go`, то ломается полпроекта, тк все зависит от `datatypes.go`, а если добавить в папку только `emergency_contacts.go`, то разъедется логика, в разных местах будет папка и файл, что странно

2024-09-23 09:14 UTC, almostinf commented on database/redis/reply/emergency_contact.go
> +func EmergencyContact(rep *redis.StringCmd) (moira.EmergencyContact, error) {
> где-то потерян глагол

Какой?

> нужна как публичная?

Да

2024-09-23 09:15 UTC, almostinf commented on database/redis/reply/emergency_contact.go
> +func EmergencyContacts(rep []*redis.StringCmd) ([]*moira.EmergencyContact, error) {
> тут тоже потерян глагол

Какой?

> нужна как публичная?

Да

2024-09-23 16:14 UTC, almostinf commented on database/redis/contact.go
> +		return contact, fmt.Errorf("failed to reply contact '%s': %w", id, err)
`reply` название уже старое, это пакет который трансформирует результаты запросов в БД к структурам в Мойре, как лучше поменять тогда текст?

2024-09-23 16:16 UTC, almostinf commented on database/redis/contact.go
> +	if getEmergencyContactErr != nil && !errors.Is(getEmergencyContactErr, database.ErrNil) {
Вопрос обсуждаемый и зависит от того, как это будет выглядеть в UI, если это будет галка внутри UI заполнения контакта, то логично было бы не просить пользователя отжимать галку, а просто удалять и то, и то. А если в UI будет отдельное окошко для этих контактов, то вариант с тем, чтобы пользователь сначала убирал эти контакты, а затем удалял основной имеет смысл быть. Но, честно, с учетом того, что связь 1-1, то удалять для меня выглядит более логичным вариантом

2024-09-23 16:16 UTC, almostinf commented on database/redis/contact.go
> +	if getEmergencyContactErr != nil && !errors.Is(getEmergencyContactErr, database.ErrNil) {
Вынесу в общее обсуждение

2024-09-23 16:26 UTC, almostinf commented on datatypes.go
> +const (
Немного поменял нейминг и убрал все типы кроме отключения нотифаера

2024-09-23 16:27 UTC, almostinf commented on database/redis/emergency_contact.go
> +			return err
Добавил кастомное сообщение

2024-09-23 16:27 UTC, almostinf commented on database/redis/emergency_contact.go
> +func saveEmergencyContactPipe(ctx context.Context, pipe redis.Pipeliner, emergencyContact moira.EmergencyContact) error {
Поменял

2024-09-30 08:31 UTC, kissken commented on database/redis/reply/emergency_contact.go
> +func EmergencyContacts(rep []*redis.StringCmd) ([]*moira.EmergencyContact, error) {
get

2024-09-30 08:31 UTC, kissken commented on database/redis/reply/emergency_contact.go
> +func EmergencyContact(rep *redis.StringCmd) (moira.EmergencyContact, error) {
get

2024-10-01 07:58 UTC, AleksandrMatsko commented on database/redis/contact.go
> +		return contact, fmt.Errorf("failed to reply contact '%s': %w", id, err)
deserialize?

2024-10-01 08:45 UTC, almostinf commented on database/redis/reply/emergency_contact.go
> +func EmergencyContact(rep *redis.StringCmd) (moira.EmergencyContact, error) {
где он должен быть? :) распиши подробнее пж

2024-10-01 08:48 UTC, almostinf commented on database/redis/reply/emergency_contact.go
> +func EmergencyContacts(rep []*redis.StringCmd) ([]*moira.EmergencyContact, error) {
выше ответил

2024-10-01 08:51 UTC, almostinf commented on datatypes.go
> +// EmergencyContactType are Moira's special internal types of problems.
окей, сделал

2024-10-01 09:23 UTC, Tetrergeru commented on database/redis/contact.go
> +	if getEmergencyContactErr != nil && !errors.Is(getEmergencyContactErr, database.ErrNil) {
Просто в рамках логики апи это разные штуки. Это в рамках логики фронта надо запросы по очереди отправлять

2024-10-02 12:27 UTC, AleksandrMatsko requested changes

2024-10-02 12:27 UTC, AleksandrMatsko commented on datatypes/emergency_contact.go
> +	HearbeatTypeNotSet   HeartbeatType = "type_not_set"
```suggestion
	HeartbeatTypeNotSet   HeartbeatType = "type_not_set"
```

2024-10-02 12:27 UTC, AleksandrMatsko commented on datatypes/emergency_contact.go
> +	case HeartbeatNotifierOff:
А почему решил сюда не добавлять `type_not_set`?

2024-10-04 11:50 UTC, kissken submitted a review, later dismissed

2024-11-01 07:59 UTC, almostinf commented on datatypes/emergency_contact.go
> +	HearbeatTypeNotSet   HeartbeatType = "type_not_set"
Исправил

2024-11-01 08:06 UTC, almostinf commented on database/redis/contact.go
> +	if getEmergencyContactErr != nil && !errors.Is(getEmergencyContactErr, database.ErrNil) {
Поправил

2024-11-01 09:18 UTC, Tetrergeru approved these changes

2024-11-01 09:25 UTC, kissken approved these changes

2024-11-01 09:33 UTC, AleksandrMatsko approved these changes

2024-11-06 04:30 UTC, AleksandrMatsko approved these changes

2024-11-06 08:18 UTC, Tetrergeru approved these changes

2025-03-28 09:21 UTC, HeavyPunk commented
PR's logic is implemented with different approach due to #1161

2025-03-28 09:21 UTC, closed without merging