Add team subscriptions and contacts
moira-alert/moira pull request #537
Opened 2020-06-08 14:47 UTC by litleleprikon

# PR Summary

In this PR I would like to introduce a team subscriptions and contacts. The core concept of teams is that users of Moira can unite to groups and manage subscriptions and contacts in this groups.

Closes/Relates #230

2021-02-19 11:01 UTC, borovskyav reviewed
В целом всё норм, все интерфейсы по делу, давай только с одним методом разберемся)

2021-02-19 11:01 UTC, borovskyav commented on database/redis/teams.go
> +func (connector *DbConnector) SaveTeamsAndUsers(teamID string, users []string, usersTeams map[string][]string) error {
Расскажи про этот метод подробнее, не понимаю какое у него использование будет?
Типа ты хочешь в одной транзакции сразу брать команду и проставлять её пользователей? Чет не сильно понятно

2021-02-19 11:21 UTC, borovskyav commented on api/handler/team.go
> +			router.Post("/", getTeamUsers)
POST?

2021-02-19 11:29 UTC, borovskyav commented on api/handler/team.go
> +		router.Patch("/", updateTeam)
Слушай, есть предложение, а давай сделаем `AddTeamUsers` и `DeleteTeamUsers` просто методами, которые в итоге просто дергают `UpdateTeam`.
Как по мне удобно иметь методы, которыми ты просто быстро добавляешь/удаляешь пользователя, но для автоматики это будет сущий ад: надо будет какие-то множества, подмножества строить, что может приводить к нелепейшим багам. Сам представь: у тебя в команде 5 пользователей: и вдруг ты своей автоматикой хочешь одного добавить, а одного удалить (уверен что через пару недель прибегут попросят интеграцию с Пандорой), вот там будет муть, вызови метод AddTeamUser, потом вызови метод DeleteTeamUser. Фу, мерзость.

А мы сейчас возьмем сделаем понятный метод Update, которым автоматика может понятно взять и перезаписать всё нафиг, но сами при этом будем иметь нормальные реализации добавления/удаления которые будем использовать на фронте.

2021-02-19 11:32 UTC, borovskyav commented on database/redis/teams.go
> +func (connector *DbConnector) SaveTeamsAndUsers(teamID string, users []string, usersTeams map[string][]string) error {
Всё, можешь не рассказывать, почитал реализацию

2021-02-20 13:11 UTC, litleleprikon commented on api/handler/team.go
> +			router.Post("/", getTeamUsers)
пофиксил

2021-02-20 13:11 UTC, litleleprikon commented on api/handler/team.go
> +		router.Patch("/", updateTeam)
добавил

2021-03-26 12:37 UTC, borovskyav requested changes

2021-03-26 12:37 UTC, borovskyav commented on api/controller/team.go
> +	// In theory probability of two exactly the same UUIDs is miserable.
го пофиксим, изи же

2021-03-29 14:14 UTC, litleleprikon commented on api/controller/team.go
> +	// In theory probability of two exactly the same UUIDs is miserable.
пофиксил

2021-04-06 08:53 UTC, borovskyav submitted a review, later dismissed

2021-04-06 10:51 UTC, androndo approved these changes

2021-04-06 10:52 UTC, merged