Implement teams database methods
moira-alert/moira pull request #584
Opened 2020-10-19 14:23 UTC by litleleprikon

# PR Summary

Implement realisation for methods of database interface that manipulated with teams

Relates #230

2021-02-19 11:41 UTC, borovskyav requested changes

2021-02-19 11:41 UTC, borovskyav commented on database/redis/teams_test.go
> +	Convey("Teams Manipulation", t, func() {
Слушай, а пробегись по быстрому по всем тестам, которые я писал на db, я там в тот момент знатно эксперементировал со структурой тестов в конвее, может тебе зайдет что-нибудь. 
Если коротко, где-то я реально обходился только одним конвеем, а где-то прям упарывался что один вызов метода БД на один конвей, в общем глянь, может найдешь что-то интересное.

Вообще как по мне самая реализация convey тестов вообще вот здесь https://github.com/moira-alert/moira/blob/master/senders/slack/slack_test.go

2021-02-19 11:42 UTC, borovskyav commented on database/redis/teams_test.go
> +	Convey("Teams Manipulation", t, func() {
В общем смотри, здесь я настаивать не буду, чет вспомнил что мы про это в какое-то время постоянного говорили, решил покидать примеров. Тесты на БД - это вообще место с большинством примеров, стоит посмотреть.

2021-02-24 11:33 UTC, androndo commented on database/redis/teams_test.go
> +	"github.com/op/go-logging"
fix merge to	`"github.com/moira-alert/moira/logging/zerolog_adapter"`

2021-03-02 10:59 UTC, litleleprikon commented on database/redis/teams_test.go
> +	Convey("Teams Manipulation", t, func() {
Ну вот интеграционные тесты на БД довольно сложная тема. Тут видишь, вызов каждого метода не идемпотентен и надо либо тестировать все методы в рамках одного теста сохраняя контекст того, что уже хранится в базе и какие изменения, либо каждый метод вызывать в отдельном конвее, каждый раз очищая БД и заполняя ее тестовыми данными, чтоб в каждом тесте иметь четкое понимание состояния БД. Второй вариант мне нравится меньше, так как в бутсреппинге БД мы будем использовать те же методы, что используем в самом тесте и это может нам аукнуться неправильной работой тестов, если в методах будет баг

2021-03-02 10:59 UTC, litleleprikon commented on database/redis/teams_test.go
> +	"github.com/op/go-logging"
пофиксил

2021-03-03 14:57 UTC, merged