Clean last check on trigger update
moira-alert/moira pull request #596
Opened 2020-11-25 12:25 UTC by litleleprikon

# PR Summary

In last check some targets have a records in MetricsToTargetRelation
dictionary. This records did not cleaned during trigger update that led
checker to use metric names from this dictionary to populate the set of
metrics to check.

Closes #593

2020-11-25 14:45 UTC, borovskyav requested changes

2020-11-25 14:45 UTC, borovskyav commented on api/controller/trigger_test.go
> +			actualLastCheck := emptyLastCheck
А разве тест не работал без этой правки? Кажется же и так всё норм, у тебя был `lastCheck`, ты его почистил, получился `emptyLastCheck`.
Так же не понял, зачем ты в saveTrigger добавил `map[string]bool{"super.metric1": true, "super.metric2": true}`.
Кароче, да, мой поинт такой - тест вроде и без правок в самом тесте должен был работать же.

2021-02-10 12:18 UTC, litleleprikon commented on api/controller/trigger_test.go
> +			actualLastCheck := emptyLastCheck
Поправил тест

2021-02-10 12:21 UTC, borovskyav approved these changes

2021-02-10 12:33 UTC, borovskyav approved these changes

2021-02-10 13:32 UTC, merged