Feature/230 connect teams and subs
moira-alert/moira pull request #609
Opened 2021-02-24 08:28 UTC by litleleprikon

# PR Summary

Additional information

Closes/Relates #issue

2021-02-24 10:59 UTC, androndo commented on api/handler/team_subscription.go
> +		subscriptionData, err := controller.CheckTeamPermissionsForSubscription(database, contactID, userLogin)
`userLogin` пихается, а там параметр `teamId`

2021-02-24 11:06 UTC, androndo commented on api/handler/team_subscription.go
> +		subscriptionData, err := controller.CheckTeamPermissionsForSubscription(database, contactID, userLogin)
видимо надо метод `CheckUserPermissionsForSubscription`

2021-03-03 19:32 UTC, litleleprikon commented on api/handler/team_subscription.go
> +		subscriptionData, err := controller.CheckTeamPermissionsForSubscription(database, contactID, userLogin)
fixed

2021-03-04 05:51 UTC, androndo approved these changes

2021-03-10 14:41 UTC, borovskyav requested changes

2021-03-10 14:41 UTC, borovskyav commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
Слушай, не такой уж это и Forbidden же. Пользователь просто ввел какую-то фигню, скорее всего это NotFound.
Forbidden это будет если ты даёшь изменять контакты или подписки команды, пользователю которого в этой команде нет. И кстати такой код я не нашел.

2021-03-10 14:41 UTC, borovskyav commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
Тоесть по сути сейчас любой пользователь может по сути менять любые контакты и подписки любой команды

2021-03-10 14:41 UTC, borovskyav commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
Ну и понятно что изменение списка пользователей сейчас у тебя тоже никак не защещенно

2021-03-10 14:41 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
Занятно что чтобы уметь работать с контактами и подписками команды, тебе надо знать и команду и подпискаID/контактID. Мы точно хотим так жить? Выглядит не очень, честно говоря.

2021-03-10 14:41 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
Очень не очень

2021-03-10 14:41 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
Максимальный уровень мерзости))

2021-03-10 14:41 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
И очень много копипасты

2021-03-10 14:53 UTC, litleleprikon commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
Вот я как раз хотел завтра заняться защитой)

2021-03-10 15:03 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
Ага, предлагаю так и сделать. Не вижу смысла их дублировать. Я еще кстати посмотреть хотел, не пришлось ли тебе ради этот базу как-то трогать и там чет дублировать, но уже не успеваю)

2021-03-10 15:04 UTC, borovskyav commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
А вообще смотри, работали раньше парни со своей автоматикой, меняли спокойно подписки, а ты им ща говоришь "ну-ка иди еще и выбирай, с какими подписками ты работать хочешь".

2021-03-11 10:05 UTC, borovskyav commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
> скорее всего это NotFound
Думаю даже честный 400

2021-03-16 13:12 UTC, litleleprikon commented on api/handler/team.go
> +		router.Route("/contacts", teamContact)
Переделал

2021-03-16 13:13 UTC, litleleprikon commented on api/controller/contact.go
> +func CheckTeamPermissionsForContact(dataBase moira.Database, contactID string, teamID string) (moira.ContactData, *api.ErrorResponse) {
Тут тоже переделал

2021-03-26 12:34 UTC, borovskyav requested changes

2021-03-29 13:44 UTC, litleleprikon commented on api/controller/subscription.go
> +	subscription.Team = teamID
Не должно меняться. Если командная подписка, там не передается `userLogin`

2021-03-29 13:45 UTC, litleleprikon commented on api/controller/subscription.go
> +func GetTeamSubscriptions(database moira.Database, teamID string) (*dto.SubscriptionList, *api.ErrorResponse) {
Ох, он вообще же сейчас не используется, его удалить можно

2021-03-29 13:49 UTC, litleleprikon commented on api/dto/team.go
> +	Team          string                   `json:"team"`
Поправил

2021-03-29 13:49 UTC, litleleprikon commented on api/dto/contact.go
> +	Team  string `json:"team,omitempty"`
Поправил

2021-04-02 10:09 UTC, borovskyav approved these changes

2021-04-06 10:44 UTC, merged