Move to go-redis (notifications)
moira-alert/moira pull request #654
Opened 2021-09-03 11:01 UTC by Dexes

2021-09-03 12:01 UTC, zhelyabuzhsky requested changes

2021-09-03 12:01 UTC, zhelyabuzhsky commented on database/goredis/reply/notification.go
> +func Notifications(responses []string, err error) ([]*moira.ScheduledNotification, error) {
Согласно комментарию (и тому, как было сделано) тут должно передаваться какой-то Cmd, а не string, нужен именно "redis DB reply"

2021-09-03 12:01 UTC, zhelyabuzhsky commented on database/goredis/reply/notification.go
> +func Notifications(responses []string, err error) ([]*moira.ScheduledNotification, error) {
В общем, аналогично предыдущему ПРу

2021-09-03 12:01 UTC, zhelyabuzhsky commented on database/goredis/reply/notification.go
> +func Notification(response string, err error) (moira.ScheduledNotification, error) {
Ну и здесь, соответственно, тоже нужен "redis DB reply"

2021-09-06 06:45 UTC, Dexes commented on database/goredis/reply/notification.go
> +func Notifications(responses []string, err error) ([]*moira.ScheduledNotification, error) {
done

2021-09-06 06:45 UTC, Dexes commented on database/goredis/reply/notification.go
> +func Notification(response string, err error) (moira.ScheduledNotification, error) {
done

2021-09-06 07:28 UTC, zhelyabuzhsky requested changes

2021-09-06 07:28 UTC, zhelyabuzhsky commented on database/goredis/reply/notification.go
> +		nf, err2 := unmarshalNotification([]byte(value), err)
nf сложно считывается, давай оставим как было, то есть "notification"

2021-09-06 07:28 UTC, zhelyabuzhsky commented on database/goredis/reply/contact.go
> +func Contact(rep *redis.StringCmd) (moira.ContactData, error) {
а ты же вроде предлагал по аналогии с Contacts сделать функцию unmarshalContact и вызывать её и в Contact, и в Contacts, разве нет?

2021-09-07 12:33 UTC, Dexes commented on database/goredis/reply/contact.go
> +func Contact(rep *redis.StringCmd) (moira.ContactData, error) {
Здесь не оказалось необходимости для этого, в Contacts прилетает массив `redis.StringCmd`

2021-09-07 12:36 UTC, Dexes commented on database/goredis/reply/notification.go
> +		nf, err2 := unmarshalNotification([]byte(value), err)
done

2021-09-07 12:55 UTC, Dexes commented on database/goredis/reply/contact.go
> +func Contact(rep *redis.StringCmd) (moira.ContactData, error) {
done

2021-09-07 12:57 UTC, zhelyabuzhsky commented on database/goredis/reply/contact.go
> +func Contact(rep *redis.StringCmd) (moira.ContactData, error) {
На всякий случай зафиксирую созвон )
Мне и прошлый вариант был норм, просто это не матчилось с тем, что ты сам устно предлагал сделать)

2021-09-07 12:57 UTC, zhelyabuzhsky approved these changes

2021-09-07 12:58 UTC, zhelyabuzhsky approved these changes

2021-09-08 08:16 UTC, KiskachiMaria approved these changes

2021-09-08 08:18 UTC, merged