Move to go-redis (metrics)
moira-alert/moira pull request #667
Opened 2021-09-15 11:17 UTC by Dexes

2021-09-15 15:45 UTC, KiskachiMaria approved these changes

2021-09-16 08:40 UTC, zhelyabuzhsky requested changes

2021-09-16 08:40 UTC, zhelyabuzhsky commented on database/goredis/metric.go
> +		if err == redis.Nil {
это точно нужно? не копипаста? проверь, пожалуйста

2021-09-16 08:48 UTC, Dexes commented on database/goredis/metric.go
> +		if err == redis.Nil {
done

2021-09-16 09:11 UTC, zhelyabuzhsky approved these changes

2021-09-16 11:37 UTC, KiskachiMaria approved these changes

2021-09-17 05:35 UTC, merged