Aditional metrics logging added on getting plot error
moira-alert/moira pull request #720
Opened 2022-01-18 10:38 UTC by dmitryanchikov

# PR Summary
Extra logging added on plot errors during handling of notification packages in notifier

2022-01-19 06:43 UTC, zhelyabuzhsky requested changes

2022-01-19 06:43 UTC, zhelyabuzhsky commented on notifier/plotting.go
> +	if err != nil {
Unit test?

2022-01-19 06:45 UTC, zhelyabuzhsky commented
Remove "PR Summary" from PR description and add example of error in log please.

2022-02-02 10:59 UTC, dmitryanchikov commented
Abandoned due to #724

2022-02-02 10:59 UTC, closed without merging