feat: Added retry logic to remote api request
moira-alert/moira pull request #760
Opened 2022-06-22 09:33 UTC by dmitryanchikov

# PR Summary

- New error type is added `ErrRemoteUnavailable`. This error is supposed to be used for cases when Remote API is unavailable, e.g. repetitively returns following errors: _401, 502, 503, 504, transport errors, timeouts_
- New config settings are added to `Remote` section in checker, api and notifier configs: 
    - RetrySeconds  `json: retry_seconds` - defines time intervals in seconds for retry calls for _errors above_, ex.: `'1 10 30'`, `'1 1`
    - HealthCheckTimeout `json: health_check_timeout` - defines timeout for calls for health check, ex.: `5s`
    - HealthCheckRetrySeconds `json: health_check_retry_seconds` defines time intervals in seconds for health check retry calls, ex.: `5 5`
- New method `makeRequestWithRetries` is added to perform calls with retries in case of getting errors from the list above. This method is applied in both health check call and fetching trigger metrics call.

# Future work
There will be follow-up PR(s) which include logic of handling of `ErrRemoteUnavailable` error in trigger check processing.

2022-07-06 09:52 UTC, zhelyabuzhsky requested changes

2022-07-06 09:52 UTC, zhelyabuzhsky commented on local/checker.yml
> +  metrics_ttl: 168h
метриксттл перенести вниз

2022-07-06 09:52 UTC, zhelyabuzhsky commented on cmd/config.go
> +		RetrySeconds:            ParseRetrySeconds(config.RetrySeconds),
Договорились, что Дима добавит getDefault по аналогии с другими существующими конфигами, и там уже станет понятно, что будет, если в ямле не задать значения для новых полей

2022-07-06 11:56 UTC, dmitryanchikov commented on cmd/config.go
> +		RetrySeconds:            ParseRetrySeconds(config.RetrySeconds),
Added to `getDefault` function in [`cmd/checker/config.go`](https://github.com/moira-alert/moira/blob/a3263521cb234d17e15ebb30bbf76edfc867a6a9/cmd/checker/config.go#L98)

2022-08-24 12:45 UTC, kissken commented on local/checker.yml
> +  metrics_ttl: 168h
-168h ?

2022-08-24 12:50 UTC, kissken commented on metric_source/remote/request.go
> +func isRemoteUnavailableStatusCode(statusCode int) bool {
теста похоже нет, проверить это надо будет

2022-08-24 12:51 UTC, kissken commented on cmd/checker/config.go
> +			MetricsTTL:              "168h",
проверить, что не "-168h"

2024-11-19 05:19 UTC, AleksandrMatsko commented
Refactored and implemented in https://github.com/moira-alert/moira/pull/1085

2024-11-19 05:19 UTC, closed without merging