fix(filter): fix regex in series by tag parser
moira-alert/moira pull request #825
Opened 2023-02-10 12:01 UTC by balalay12

# PR Summary
This PR fix `series by tags` parser. 
1. Fix regular expression for correct work with regular expressions in tags. Example: `seriesByTag("respCode=~^(4|5)\d{2}")`
2. Now transform function applied to every tag spec. Not for whole value in `seriesByTag()`.
3. If spec was tranformed change `operator` from `equal` to `match`.

Closes #823

2023-02-13 05:38 UTC, kissken commented
before merge we will test it on feature branch :)

2023-02-15 09:58 UTC, Tetrergeru commented on filter/series_by_tag.go
> +		result                                     = input
I think it would be more ideomatic to use `:=` instead of the var bloc, if it is possible
```suggestion
		result := input
```

2023-02-15 10:15 UTC, Tetrergeru commented on filter/series_by_tag.go
> +		correctLengthOfMatchedWildcardIndexesSlice = 4
Maybe we sould make it a constant and also use in `ParseSeriesByTag`, where magic number 4 is used

2023-02-15 10:18 UTC, Tetrergeru requested changes
Left some minor suggestions

2023-02-17 11:04 UTC, Tetrergeru submitted a review, later dismissed

2023-03-01 09:02 UTC, kissken commented
потестили, результаты:

seriesByTag("name=~^a.(b|c).d") ✅
seriesByTag('name=~^a.(b|c).d') ❌
seriesByTag('name=a.b.c')❌

2023-04-20 06:46 UTC, kissken commented
последние правки были ок

2023-04-20 06:46 UTC, kissken commented
влила мастер в ветку

2023-04-20 07:13 UTC, kissken approved these changes

2023-04-20 08:22 UTC, Tetrergeru approved these changes

2023-04-26 05:57 UTC, merged