fix(filter): fix support custom retention for tagged metrics
moira-alert/moira pull request #950
Opened 2023-10-27 11:16 UTC by kissken

2023-10-30 08:43 UTC, Tetrergeru approved these changes

2023-10-30 08:48 UTC, almostinf approved these changes

2023-10-31 09:56 UTC, kissken commented
/build

2024-08-07 10:16 UTC, almostinf commented
/build

2024-08-07 11:13 UTC, almostinf approved these changes

2024-08-07 13:24 UTC, Tetrergeru commented on filter/cache_storage.go
> +				Msg(`Invalid retentions format, it is correct to write in the format "retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ..."`)
А почему мы в тексте лога пишем инструкцию по испольщованию формата ретеншена? Может завести ошибку хотя бы и через `.Error()` передавать? На случай, если, например, когда-нибудь разные ошибки в этом месте появятся

2024-08-07 14:27 UTC, almostinf approved these changes

2024-08-07 14:39 UTC, Tetrergeru submitted a review, later dismissed

2024-08-09 04:39 UTC, AleksandrMatsko requested changes
Надушнил немного...

2024-08-09 04:39 UTC, AleksandrMatsko commented on filter/cache_storage.go
> +	defaultRetention = 60
Мб константой эту штуку сделать? Вроде нигде ей ничего не присваивается.

2024-08-09 04:39 UTC, AleksandrMatsko commented on filter/cache_storage.go
> +	InvalidRetentionsFormatErr = errors.New("Invalid retentions format, it is correct to write in the format 'retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...'")
Ошибки не должны быть с маленькой буквы? (у меня Goland подчеркнул)

2024-08-09 09:10 UTC, almostinf commented on filter/cache_storage.go
> +	defaultRetention = 60
Сделал

2024-08-09 09:11 UTC, almostinf commented on filter/cache_storage.go
> +	InvalidRetentionsFormatErr = errors.New("Invalid retentions format, it is correct to write in the format 'retentions = timePerPoint:timeToStore, timePerPoint:timeToStore, ...'")
Резонно, ошибка на текущий момент по сути наша внутренняя и снаружи не нужна

2024-08-09 09:11 UTC, almostinf approved these changes

2024-08-09 09:12 UTC, almostinf commented
/build

2024-08-09 12:51 UTC, Tetrergeru approved these changes

2024-08-12 03:30 UTC, AleksandrMatsko approved these changes

2024-08-12 07:22 UTC, merged